In [ ]:
"""
To Do:
Import SVM modules
"Fix up" Data importing/processing
Analysis using SVMs (multiple SVMs, for each category)
Multiple Kernels


"""

In [12]:
import numpy as np
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt
# import svm...
from sklearn import preprocessing # preprossing is what we do with the data before we run the learning algorithm
from sklearn.model_selection import train_test_split 
from sklearn.metrics import precision_recall_fscore_support
%matplotlib inline

# Importing the dataset

In [13]:
# Importing examples of red wine
df_red = pd.read_csv('data/winequality-red.csv', delimiter=';')
df_red.head(6)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5

In [14]:
# Importing examples of white wine
df_white = pd.read_csv('data/winequality-white.csv', delimiter=';')
df_white.head(6)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
5,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6

In [15]:
# Reduce data to random samples of size N
# Can set N to whatever you want
N = 200 
df_red = df_red.sample(N)
df_white = df_white.sample(N)

In [16]:
print("Red Wine:")
display(np.round(df_red.describe()))
print("White Wine:")
display(np.round(df_white.describe()))

Red Wine:

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0
mean,8.0,1.0,0.0,3.0,0.0,16.0,47.0,1.0,3.0,1.0,10.0,6.0
std,2.0,0.0,0.0,1.0,0.0,10.0,33.0,0.0,0.0,0.0,1.0,1.0
min,5.0,0.0,0.0,1.0,0.0,3.0,6.0,1.0,3.0,0.0,9.0,4.0
25%,7.0,0.0,0.0,2.0,0.0,8.0,23.0,1.0,3.0,1.0,10.0,5.0
50%,8.0,1.0,0.0,2.0,0.0,14.0,38.0,1.0,3.0,1.0,10.0,6.0
75%,9.0,1.0,0.0,3.0,0.0,22.0,62.0,1.0,3.0,1.0,11.0,6.0
max,16.0,1.0,1.0,14.0,0.0,51.0,152.0,1.0,4.0,1.0,14.0,8.0

White Wine:

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0
mean,7.0,0.0,0.0,6.0,0.0,35.0,136.0,1.0,3.0,0.0,11.0,6.0
std,1.0,0.0,0.0,5.0,0.0,17.0,45.0,0.0,0.0,0.0,1.0,1.0
min,5.0,0.0,0.0,1.0,0.0,4.0,10.0,1.0,3.0,0.0,9.0,4.0
25%,6.0,0.0,0.0,2.0,0.0,23.0,105.0,1.0,3.0,0.0,10.0,5.0
50%,7.0,0.0,0.0,5.0,0.0,33.0,131.0,1.0,3.0,0.0,10.0,6.0
75%,7.0,0.0,0.0,9.0,0.0,46.0,169.0,1.0,3.0,1.0,12.0,7.0
max,14.0,1.0,1.0,18.0,0.0,86.0,245.0,1.0,4.0,1.0,14.0,8.0

In [17]:
# Get column names
column_names = list(df_red)
for i in range(len(column_names)):
    print(i, column_names[i])

0 fixed acidity
1 volatile acidity
2 citric acid
3 residual sugar
4 chlorides
5 free sulfur dioxide
6 total sulfur dioxide
7 density
8 pH
9 sulphates
10 alcohol
11 quality

In [18]:
# Add column of zeros to red wine values
# TODO: combine all of white and red into one DF with a new column "red" = 1, 0
red = df_red.values
#print(red[:1, :])
zeros = np.zeros((red.shape[0], 1))
red = np.hstack((red, zeros))
#print(red[:1, :])

In [19]:
# Add column of ones to white wine values
white = df_white.values
ones = np.ones((white.shape[0], 1))
white = np.hstack((white, ones))
#print(white[:1, :])

# Supervised Analysis

## Predicting wine quality using SVMs

### Data Preprocessing

In [22]:
# Separate y's from red
red_y = red[:, -1]
red_y = np.reshape(red_y, (len(red_y), 1))
red_x = red[:, :-1]
# Separate y's from white
white_y = white[:, -1]
white_y = np.reshape(white_y, (len(white_y), 1))
white_x = white[:, :-1]

# print("red-y shape:", red_y.shape)
# print("white-y shape", white_y.shape)
# Combine red and white data into a single matrix
x = np.vstack((red_x, white_x))
# Scale x data
x_scale = preprocessing.scale(x)

# Combine y's from red and white into a single vector
y = np.vstack((red_y, white_y))

# print("X shape:", x_scale.shape)
# print("y shape:", y.shape)
# print(x_scale[:6, :])
# print(y[:6, :])

# Splitting data into training and test data

x_train, x_test, y_train, y_test = train_test_split(x_scale, y)
print(x_train.shape)
print(y_train.shape)

(300, 12)
(300, 1)

### Using SVMs